// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('myApp.directives', []).directive('appVersion', [
    'version', function(version) {
      return function(scope, elm, attrs) {
        return elm.text(version);
      };
    }
  ]).directive('hoverShow', function() {
    return {
      link: function(scope, elm, attrs) {
        elm.bind('mouseover', {
          attrs: attrs
        }, function(ev) {
          return elm.closest('.projects').find('.' + ev.data.attrs.hoverShow).show();
        });
        return elm.bind('mouseout', {
          attrs: attrs
        }, function(ev) {
          return elm.closest('.projects').find('.' + ev.data.attrs.hoverShow).hide();
        });
      }
    };
  }).directive('customScroll', function() {
    return {
      link: function(scope, elm, attrs) {
        return $(elm).mCustomScrollbar({
          theme: 'dark-2'
        });
      }
    };
  }).directive('carousel', function() {
    return {
      scope: {
        carousel: '='
      },
      link: function(scope, elm, attrs) {
        var cIndex, carousel, img;
        carousel = scope.carousel;
        img = elm.find('img')[0];
        cIndex = 0;
        img.src = carousel[cIndex];
        return setInterval(function() {
          setTimeout(function() {
            return $(img).css({
              opacity: 0.1
            });
          }, 100);
          if (cIndex < carousel.length - 1) {
            cIndex += 1;
          } else {
            cIndex = 0;
          }
          img.src = carousel[cIndex];
          return setTimeout(function() {
            return $(img).css({
              opacity: 1
            });
          }, 200);
        }, 4500);
      }
    };
  });

}).call(this);
