// Generated by CoffeeScript 1.3.1
(function() {

  angular.module('myApp', ['myApp.filters', 'myApp.services', 'myApp.directives']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/who_am_i', {
        templateUrl: 'partials/who_am_i.html',
        controller: MyCtrl1
      });
      $routeProvider.when('/timeline', {
        templateUrl: 'partials/timeline.html',
        controller: MyCtrl2
      });
      return $routeProvider.otherwise({
        redirectTo: '/who_am_i'
      });
    }
  ]);

}).call(this);
